## Save model in Pytorch

In [1]:
# import python modules
import torch


def set_seeds(seeds):
    torch.manual_seed(seeds)
    torch.cuda.manual_seed(seeds)
    torch.backends.cudnn.deterministic = True

set_seeds(12)

In [2]:
# define a model
class MyModel(torch.nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.fc = torch.nn.Linear(10, 2)

    def forward(self, x):
        x = self.fc(x)
        return x


In [6]:
# Save the whole model
model = MyModel()

x = torch.rand(1, 10)
y1 = model(x)
print(y1)

torch.save(model, 'assets/weights/model.pth')

# Load the whole model
loaded_model = torch.load('assets/weights/model.pth')

y2 = loaded_model(x)
print(y2)

tensor([[ 0.1844, -0.3004]], grad_fn=<AddmmBackward0>)
tensor([[ 0.1844, -0.3004]], grad_fn=<AddmmBackward0>)


C:\Users\43757\AppData\Local\Temp\ipykernel_39236\4080442247.py:11: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded_model = torch.load('assets/weights/model.pth')


In [7]:
# Save the parameters only
model = MyModel()

x = torch.rand(1, 10)
y1 = model(x)
print(y1)

torch.save(model.state_dict(), 'assets/weights/model_params.pth')

# Load the parameters
loaded_model = MyModel()
loaded_model.load_state_dict(torch.load('assets/weights/model_params.pth'))

y2 = loaded_model(x)
print(y2)

tensor([[-0.2779, -0.2586]], grad_fn=<AddmmBackward0>)
tensor([[-0.2779, -0.2586]], grad_fn=<AddmmBackward0>)


C:\Users\43757\AppData\Local\Temp\ipykernel_39236\3054238626.py:12: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded_model.load_state_dict(torch.load('assets/weights/mod