# Pytorch 保存模型

In [11]:
# import python modules
import torch


def set_seeds(seeds):
    torch.manual_seed(seeds)
    torch.cuda.manual_seed(seeds)
    torch.backends.cudnn.deterministic = True

set_seeds(12)

In [12]:
# define a model
class MyModel(torch.nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.fc = torch.nn.Linear(10, 2)

    def forward(self, x):
        x = self.fc(x)
        return x


In [17]:
# 保存整个模型
model = MyModel()

x = torch.rand(1, 10)
y1 = model(x)
print(y1)

torch.save(model, 'model.pth')

# 加载整个模型
loaded_model = torch.load('model.pth')

y2 = loaded_model(x)
print(y2)

tensor([[-0.2554, -0.0882]], grad_fn=<AddmmBackward0>)
tensor([[-0.2554, -0.0882]], grad_fn=<AddmmBackward0>)


In [20]:
# 只保存模型的参数
model = MyModel()

x = torch.rand(1, 10)
y1 = model(x)
print(y1)

torch.save(model.state_dict(), 'model_params.pth')

# 加载模型的参数
loaded_model = MyModel()
loaded_model.load_state_dict(torch.load('model_params.pth'))

y2 = loaded_model(x)
print(y2)

tensor([[ 0.2389, -0.9291]], grad_fn=<AddmmBackward0>)
tensor([[ 0.2389, -0.9291]], grad_fn=<AddmmBackward0>)
